### ISSUE TITLE
`CI=true rails test` fails to load.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-themes-tailwind_css#2]
```
andrewculver@Andrews-MacBook-Pro-2 bullet_train-themes-tailwind_css % CI=true rails test 
/Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/core_ext/hash/keys.rb:52:in `block in assert_valid_keys': Unknown key: :enable_updates. Valid keys are: :class_name, :anonymous_class, :primary_key, :foreign_key, :dependent, :validate, :inverse_of, :strict_loading, :autosave, :before_add, :after_add, :before_remove, :after_remove, :extend, :counter_cache, :join_table, :index_errors (ArgumentError)
	from /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/core_ext/hash/keys.rb:50:in `each_key'
	from /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/core_ext/hash/keys.rb:50:in `assert_valid_keys'
	from /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.2.4/lib/active_record/associations/builder/association.rb:70:in `validate_options'
	from /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.2.4/lib/active_record/associations/builder/association.rb:43:in `create_reflection'
	from /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.2.4/lib/active_record/associations/builder/association.rb:32:in `build'
	from /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.2.4/lib/active_record/associations.rb:1467:in `has_many'
	from /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bullet_train-1.0.63/app/models/concerns/teams/base.rb:7:in `block in <module:Base>'
	from /Users/andrewculver/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/concern.rb:136:in `class_eval'
...
```

`updatable` is introduced by CableReady, which is included by the `bullet_train` package. Not sure why this isn't loading automatically like it does in other repositories.

**Comment by gazayas** [comment]
@andrewculver Setting `config.eager_load` to `false` in [test/dummy/config/environments/test.rb](https://github.com/bullet-train-co/bullet_train-themes-tailwind_css/blob/dced6fd74e10087e8af39a98371fc59d3cf1f4fb/test/dummy/config/environments/test.rb#L17) fixes the issue, but I'm not sure what the best answer is here since the comment says we don't need this when running a single test locally (`rails test` here only runs one test), but the comment also says that it's a good idea to use in a continuous integration system, which is why I'm guessing we're reading the CI environment variable in the first place.

I'm not sure if helps knowing that `eager_load` here is affects the outcome, but if anything I can swing back and check this one out again sometime soon.

**Comment by andrewculver** [comment]
@gazayas Yeah, this one needs to be figured out. Basically I use `CI=true` to enable eager loading. It’s important that CI do eager loading, and important that the test suite works when it is enabled. Haven’t a clue what the issue is here when all the other packages so far have had no issue.

**Comment by gazayas** [comment]
@andrewculver Got it, I'll take another look then.

**Comment by jagthedrummer** [comment]
Closing this since this repo is no longer used, and tests on `bullet_train-themes-tailwind_css` in the `core` repo are passing in CI.
